version: "3.7"

services:

  # PHP-FPM - Service
  app:
    build:
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: ./docker-files/php/app.Dockerfile
    container_name: app_laralib
    restart: unless-stopped
    tty: true
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  # NGINX - Service
  webserver:
    build:
      context: ./
      dockerfile: ./docker-files/nginx/server.Dockerfile
    container_name: webserver_laralib
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "8143:443"
    volumes:
      - ./:/var/www
      - ./docker-files/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  # MariaDB - Service
  db:
    build:
      context: ./
      dockerfile: ./docker-files/mysql/db.Dockerfile
    container_name: db_laralib
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laralib
      MYSQL_ROOT_PASSWORD: laralib
    #volumes:
      - mariadbdata:/var/lib/mysql
      - ./docker-files/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

# Volumes
volumes:
  mariadbdata:
    driver: local

# Networks
networks:
  app-network:
    driver: bridge
